spring.application.name=letsCheckQuiz
server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5432/letsCheckQuiz
spring.datasource.username=khurana
spring.datasource.password=khurana
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect